spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    database: mysql

    hibernate:
      ddl-auto: update
    # Hibernate ddl auto (create, create-drop, validate, update)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:

  servlet:
      multipart:
      max-request-size: 20MB
      max-file-size: 20MB
